### ISSUE TITLE
Support for internationalization

### ISSUE THREAD

**Issue by marcschw** [tim-smart/flutter-emulators-screenshots-demo#3]
Hi,
this is a great replacement for the screenshots package, thank you for creating it!

The only thing I'm missing is an easy way to switch the languages in the emulators so I can create screenshots in different language versions of my app at once. This was pretty straightforward in the screenshots package, it's probably also possible here but I probably lack the knowledge to do it without help.

Thanks!
Marcel

**Comment by tim-smart** [comment]
I looked into this, and there isn't a reliable way to set the locale at the device level. It looks like Google has dropped support for some cases.

But you can do it at the application level with 0.2.3. I have updated this repo with an example.

You would setup the locales to test against here: https://github.com/tim-smart/flutter-emulators-screenshots-demo/blob/main/tools/screenshots.dart#L27

You would pass the locale to your app here: https://github.com/tim-smart/flutter-emulators-screenshots-demo/blob/main/test_driver/main.dart#L17
