### ISSUE TITLE
How to run tests without running screenshots?

### ISSUE THREAD

**Issue by gslender** [tim-smart/flutter-emulators-screenshots-demo#6]
Can you provide some advice/direction on how you're supposed to just run tests using the driver setup so that we/I can just verify the tests are running correctly without having to run the entire screenshot capture emulator? or is that not possible?

The reason is that I'm getting success with iOS but not getting equal results for Android - for some reasons the tests are not navigating the widget tree equally between, and I'd like to step through the tests more easily than what it take for them to run via the emulators/screenshot code. Just not sure how to launch it with just the test code ??

**Comment by tim-smart** [comment]
You can now do this by passing `disable: true` to the `screenshotHelper` method :)
